version: '3'
services:
  xrayr:
    image: crackair/xrayr:latest
    volumes:
      - ./config.yml:/etc/XrayR/config.yml # 映射配置文件夹
      - ./dns.json:/etc/XrayR/dns.json
      - ./rulelist:/etc/XrayR/rulelist
      - /cert/fullchain.pem:/cert/fullchain.pem
      - /cert/privkey.pem:/cert/privkey.pem
    restart: always
    network_mode: host